name: Publish Backend
on:
  push:
    branches:
      - main
jobs:
  release:
    concurrency:
      group: ${{ github.ref }}
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          #key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: cd /home/cicd/aspnet-core-ci-cd && git pull && sh start.sh
